name: zebra-noise
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - backcall=0.2.0
  - certifi=2024.8.30
  - comm=0.2.2
  - contourpy=1.3.0
  - cycler=0.12.1
  - debugpy=1.8.6
  - decorator=5.1.1
  - executing=2.1.0
  - fastcluster=1.2.6
  - ffmpeg=6.1.2
  - fontconfig=2.14.2
  - fonttools=4.54.1
  - freetype=2.12.1
  - imageio=2.35.1
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.12.0
  - jedi=0.19.1
  - joblib=1.4.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.7
  - lazy-loader=0.4
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - opencv=4.10.0
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - patsy=0.5.6
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pyparsing=3.1.4
  - pyside6=6.7.3
  - python=3.9.19
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - pytz=2024.2
  - pywavelets=1.5.0
  - pyzmq=26.2.0
  - scikit-image=0.24.0
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.1.0
  - six=1.16.0
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - threadpoolctl=3.5.0
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.2.6
  - zipp=3.20.2
  - zstd=1.5.6
  - pip:
      - filelock==3.15.4
      - fsspec==2024.9.0
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.2.1
      - sympy==1.13.1
      - tifffile==2024.8.30
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tensorly==0.9.0
      - tqdm==4.67.1
prefix: /home/leonk/anaconda3/envs/zebra-noise
